### PR TITLE
Do not throw unexpected FFMpegException on FFProbe cancallation. Fixes  #594

### LINKED ISSUE #594: Unexpected "FFMpegException: ffprobe exited with non-zero exit-code (-1 - )" after a cancellation request.
# Environment
* FFMpeg rev. a599c48511cb9ba059b00e3c3a4276650388ec4b
* ffprobe version: 7.1.1-full
  <details><summary>Full version info</summary>

     ````
      ffprobe version 7.1.1-full_build-www.gyan.dev Copyright (c) 2007-2025 the FFmpeg developers
      built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
      configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
      libavutil      59. 39.100 / 59. 39.100
      libavcodec     61. 19.101 / 61. 19.101
      libavformat    61.  7.100 / 61.  7.100
      libavdevice    61.  3.100 / 61.  3.100
      libavfilter    10.  4.100 / 10.  4.100
      libswscale      8.  3.100 /  8.  3.100
      libswresample   5.  3.100 /  5.  3.100
      libpostproc    58.  3.100 / 58.  3.100
     ````

  </details> 
* OS: Win11
* dotnet: 9.0.305
* TFM: `net8.0`

# Steps to reproduce

Run the following code (add `GlobalFFOptions` to set binaries path and update path to the test mp4 as needed). This code starts the bunch of the snapshot generation tasks in parallel then cancels them all.

```csharp
WarmUp();

var mp4 = "SampleVideo_1280x720_1mb.mp4";
var cts = new CancellationTokenSource();
var token = cts.Token;
var semaphore = new SemaphoreSlim(Environment.ProcessorCount, Environment.ProcessorCount);

var tasks = Enumerable.Range(0, 50).Select(x => Task.Run(async () =>
{
    await semaphore.WaitAsync();
    try
    {
        var tempThumbnailPath = Path.GetTempFileName();
        File.Delete(tempThumbnailPath);
        tempThumbnailPath = Path.ChangeExtension(tempThumbnailPath, ".png");

        var analysis = await FFProbe.AnalyseAsync(mp4, cancellationToken: token);
        var (args, opts) =
            SnapshotArgumentBuilder.BuildSnapshotArguments(mp4, tempThumbnailPath, analysis,
                captureTime: TimeSpan.FromSeconds(2));

        var res = await args.OutputToFile(tempThumbnailPath, true, opts)
            .CancellableThrough(token)
            .ProcessAsynchronously(throwOnError: true);

        return res ? tempThumbnailPath : throw new Exception("Failed to generate thumbnail.");
    }
    finally
    {
        semaphore.Release();
    }
}, token)).ToList();

//wait 2 tasks to finish then cancel all
await Task.WhenAny(tasks);
await Task.WhenAny(tasks);
await cts.CancelAsync();
cts.Dispose();

foreach (var task in tasks)
{
    try
    {
        await task;
    }
    catch (Exception e)
    {
        Console.WriteLine($"{e.GetType().Name}: {e.Message}");
    }
}

semaphore.Dispose();

void WarmUp()
{
    //warmup, see https://github.com/rosenbjerg/FFMpegCore/issues/580
    FFProbeHelper.VerifyFFProbeExists(GlobalFFOptions.Current);
    FFMpegHelper.VerifyFFMpegExists(GlobalFFOptions.Current);
    FFMpeg.GetCodecs();
    FFMpeg.GetContainerFormats();
    FFMpeg.GetPixelFormats();
}
```

* comment out the `await cts.CancelAsync();` line to make sure that without cancellation processing finishes without exceptions or other problems
* uncomment `await cts.CancelAsync();` back and run again.

## Expected behavior

A lot of `OperationCacnelledException`s. Some tasks was finished successfully before the cancellation was requested. No other exceptions.

## Actual behavior

In addition to the `OperationCanceledException` we got a lot of the `FFMpegException: ffprobe exited with non-zero exit-code (-1 - )` which is completely unexpected.

### PR DESCRIPTION
**Pull request by snechaev**
FFProbe helper will now throw an `OperationCancelledException` if a cancellation was requested, rather than an `FFMpegException`, even if the ffprobe exited with a non-zero exit code. This is reasonable behavior as the any results are usesless after the cancellation and any exceptions except for an `OperationCancelledException` and similar are unexpected.

A test was added to verify the initial problem and the fix.

Fixes  #594

### CODE REVIEW

File: FFMpegCore/FFProbe/FFProbe.cs [hunk 1]
```diff
@@ -212,8 +212,11 @@ private static void ThrowIfInputFileDoesNotExist(string filePath)
         }
     }
 
-    private static void ThrowIfExitCodeNotZero(IProcessResult result)
+    private static void ThrowIfExitCodeNotZero(IProcessResult result, CancellationToken cancellationToken = default)
     {
+        // if cancellation requested, then we are not interested in the exit code, just throw the cancellation exception
+        // to get consistent and expected behavior.
+        cancellationToken.ThrowIfCancellationRequested();
```
Comment (snechaev) [inline FFMpegCore/FFProbe/FFProbe.cs]: I'm feeling slightly unsure about this. The function name claims that it will throw in case of non-zero exit code. However, the fixed implementation will also throw if the cancellation is requested even if the exit code is zero.

Comment (rosenbjerg) [reply FFMpegCore/FFProbe/FFProbe.cs]: I agree that it doesnt fit that well with this method. Maybe would be clearer if `ThrowIfCancellationRequested` is just called right before `ThrowIfExitCodeNotZero`?

Comment (snechaev) [reply FFMpegCore/FFProbe/FFProbe.cs]: I can see the following options here:
1. Move the `ThrowIfCancellationRequested()` call under the `if(exitCode != 0)` check. In this case all the changes will be in one place and method contract would be kept intact.
2. Move the cancellation check outside the method. This makes the code clear and easy to understand, but it will be fragile. It will be too easy to forget to add the cancellation check before the `ThrowIfExitCodeNotZero()` during future code edits, so we will get the regression.
3. Rename the method to something more general like `CheckResult` or `HandleCompletion`, so the name will not conflict with the logic. I do not like this option, tbh.  The current name absolutely perfectly describes what the function does without any unnecessary generalisation.

Comment (snechaev) [reply FFMpegCore/FFProbe/FFProbe.cs]: I took the liberty of making an update with the cancellation check moved inside the exit code check condition. If you consider this version suboptimal, please let me know and I will rework the implementation to perform a check for cancellation before calling `ThrowIfNonZeroExitCode()` (and not inside).

Comment (rosenbjerg) [reply FFMpegCore/FFProbe/FFProbe.cs]: I think it is misleading to have `ThrowIfExitCodeNotZero` handle anything other than throwing if exit-code is not zero. Then I'd prefer that we just call `ThrowIfCancellationRequested` before calling `ThrowIfNonZeroExitCode`. If the fragility of this becomes a concern, we can add another method that delegates to both these `Throw*` methods to streamline the throwing

Comment (snechaev) [reply FFMpegCore/FFProbe/FFProbe.cs]: Got it! The code has been updated.

**Review by rosenbjerg — APPROVED** [review]
Looks great, thank you for the contribution!
